name: iss_tracker_app
description: "Track the International Space Station (ISS) and see its current location in real-time."
publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  intl: ^0.20.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  logging: ^1.3.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3

flutter:

  uses-material-design: true

  assets:
    - assets/anim/iss_animation.json
    - assets/img/app_icon.jpg
