// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcetvxFcbFVijiWS3QKCrad_QvIc03gU',
    appId: '1:153637931490:web:679d4e54d6911eca7b11bb',
    messagingSenderId: '153637931490',
    projectId: 'iss-tracker-8201a',
    authDomain: 'iss-tracker-8201a.firebaseapp.com',
    storageBucket: 'iss-tracker-8201a.firebasestorage.app',
    measurementId: 'G-YK11767YTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj485okP_q9NSjtYOurJjkGPGWK-qlezI',
    appId: '1:153637931490:android:3178dfe02625878f7b11bb',
    messagingSenderId: '153637931490',
    projectId: 'iss-tracker-8201a',
    storageBucket: 'iss-tracker-8201a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVD4ScyBq6yRT69tQ65z3yAadTuXymjM',
    appId: '1:153637931490:ios:bfab998a711c91fb7b11bb',
    messagingSenderId: '153637931490',
    projectId: 'iss-tracker-8201a',
    storageBucket: 'iss-tracker-8201a.firebasestorage.app',
    iosBundleId: 'com.krzshipon.issTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnVD4ScyBq6yRT69tQ65z3yAadTuXymjM',
    appId: '1:153637931490:ios:bfab998a711c91fb7b11bb',
    messagingSenderId: '153637931490',
    projectId: 'iss-tracker-8201a',
    storageBucket: 'iss-tracker-8201a.firebasestorage.app',
    iosBundleId: 'com.krzshipon.issTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGcetvxFcbFVijiWS3QKCrad_QvIc03gU',
    appId: '1:153637931490:web:769d17fd1f55f3ea7b11bb',
    messagingSenderId: '153637931490',
    projectId: 'iss-tracker-8201a',
    authDomain: 'iss-tracker-8201a.firebaseapp.com',
    storageBucket: 'iss-tracker-8201a.firebasestorage.app',
    measurementId: 'G-ZDXVCLMPMH',
  );
}
